/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sovietstruggle;

/**
 *
 * @author chiggie
 */
public class AreaPanel extends javax.swing.JPanel
{

  /**
   * Creates new form areaPanel
   */
  public AreaPanel()
  {
    initComponents();
    area = null;
  }
  
  public AreaPanel(Area area, SovietStruggleGUI game, int xLocation, int yLocation)
  {
    this.area = area;
    this.game = game;
    this.xLocation = xLocation;
    this.yLocation = yLocation;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    areaButton = new javax.swing.JButton();

    areaButton.setBackground(java.awt.Color.green);
    areaButton.setIcon(TextFormat.scaleImage(SovietStruggleGUI.IMG_PATH + "map_marker.png", 20)
    );
    areaButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    areaButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        areaButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(areaButton)
        .addContainerGap(102, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(areaButton)
        .addContainerGap(98, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void areaButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_areaButtonActionPerformed
  {//GEN-HEADEREND:event_areaButtonActionPerformed
    game.showMainMapMenu(this);
  }//GEN-LAST:event_areaButtonActionPerformed

  public void updateBounds()
  {
    setBounds(xLocation, yLocation, 20, 20);
  }

  public int getX()
  {
    return xLocation;
  }

  public int getY()
  {
    return yLocation;
  }
  
  public boolean hasAlliedArmy()
  {
    return area.hasAlliedArmy();
  }
  
  private Area area;
  private SovietStruggleGUI game;
  private int xLocation, yLocation;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton areaButton;
  // End of variables declaration//GEN-END:variables
}
