/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sovietstruggle;

/**
 *
 * @author 19changc
 */
public class DecisionPanel extends javax.swing.JPanel
{
  private SovietStruggleGUI game;

  /**
   * Creates new form DecisionPanel
   */
  public DecisionPanel()
  {
    initComponents();
  }
  
  public DecisionPanel(Decision decision)
  {
    this.decision = decision;
    initComponents();
    game = null;
  }
  
  public DecisionPanel(Decision decision, SovietStruggleGUI game)
  {
    this.decision = decision;
    this.game = game;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    text = new javax.swing.JLabel();
    takeButton = new javax.swing.JButton();

    setBackground(new java.awt.Color(255, 255, 255));
    setToolTipText(decision.getDescription());

    text.setText(decision.toString());

    takeButton.setText("Take");
    takeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        takeButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(takeButton)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(text))
          .addGroup(layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(takeButton)))
        .addGap(12, 12, 12))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void takeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_takeButtonActionPerformed
  {//GEN-HEADEREND:event_takeButtonActionPerformed
    decision.take();
    game.updateDecisionArea();
  }//GEN-LAST:event_takeButtonActionPerformed

  private Decision decision;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton takeButton;
  private javax.swing.JLabel text;
  // End of variables declaration//GEN-END:variables
}
